### ISSUE TITLE
Improve eaxample: ANSYS DPF-Post: Transient Anaysis (access time steps)

### ISSUE THREAD

**Issue by natter1** [ansys/pydpf-post#42]
I couldn't figure out how to access results (like displacement) over time when using `dpf-post` with a transient simulation. The only [example for transient analysis](https://postdocs.pyansys.com/examples/01-Different-analysis-types/04-transient-analysis.html#sphx-glr-examples-01-different-analysis-types-04-transient-analysis-py) also does not show how to do it (in fact I don't know which result is used there for the plots - the last substep?). So how is it done? Also, I would suggest to improve the example, to show this.

**Comment by natter1** [comment]
Hmm, I found a "solution" for my problem (should be similar for the examle);

```
    time_steps_list = solution.time_freq_support.time_frequencies.data_as_list
    x_data = []
    y_data = []
    for time in time_steps_list[:-1]:
        x_data.append(time)
        displacement_fields__selection = solution.displacement(named_selection=named_selection, time=time)
        tip_disp = displacement_fields__selection.vector.get_data_at_field(0)[0]
        # tip_disp_norm = displacement_fields__selection.norm.get_data_at_field(0)[0]
        y_data.append(tip_disp[2])
```

But I'm pretty sure thats not how it should be done, because its extremly slow (its only one node in the selection, but each timestep in the for-loop takes roughly 0.2s). Also, for some reason I have to exclude the last timestep, or it crashes when reaching `tip_disp = displacement_fields__selection.vector.get_data_at_field(0)[0]`

```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Program Files\JetBrains\PyCharm 2021.2.2\plugins\python\helpers\pydev\_pydev_bundle\pydev_umd.py", line 198, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm 2021.2.2\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "D:/myPython/Al_cantilever/only_post_process.py", line 8, in <module>
    post_process_dpf(result_path, geo_data)
  File "D:\myPython\Al_cantilever\post_dpf.py", line 87, in post_process_dpf
    get_tip_movement(solution)
  File "D:\myPython\Al_cantilever\post_dpf.py", line 64, in get_tip_movement
    tip_disp = displacement_fields__selection.vector.get_data_at_field(0)[0]
  File "D:\myPython\Al_cantilever\venv\lib\site-packages\ansys\dpf\post\vector.py", line 28, in vector
    return super()._get_result_data(self._operator_name, self._data_sources, self._model)
  File "D:\myPython\Al_cantilever\venv\lib\site-packages\ansys\dpf\post\result_object.py", line 54, in _get_result_data
    return ResultData(operator_name=operator_name, data_sources=data_sources,
  File "D:\myPython\Al_cantilever\venv\lib\site-packages\ansys\dpf\post\result_data.py", line 52, in __init__
    self._evaluator = ResultEvaluator(operator_name, data_sources, model, elem_average,
  File "D:\myPython\Al_cantilever\venv\lib\site-packages\ansys\dpf\post\result_evaluation.py", line 129, in __init__
    time2 = tfq.get_frequency(cumulative_index=(lower_index+1))
  File "D:\myPython\Al_cantilever\venv\lib\site-packages\ansys\dpf\core\time_freq_support.py", line 259, in get_frequency
    return self._get_frequency(step, substep, cumulative_index, cplx)
  File "D:\myPython\Al_cantilever\venv\lib\site-packages\ansys\dpf\core\errors.py", line 103, in wrapper
    raise DPFServerException(details) from None
ansys.dpf.core.errors.DPFServerException: cumulative index out of range

```

**Comment by PProfizi** [comment]
Hi @natter1 !
I've started looking at this and clearly it seems the Result objects are for now not meant to be scoped on a time_freq_support containing more than one value.
I suggest using the PyDPF-Core capabilities for now, as shown in this [Transient Analysis Result Example](https://dpfdocs.pyansys.com/examples/01-static-transient/00-basic_transient.html).
Once the PyDPF-Post capabilities are able to do this, the exemple should indeed be updated.
I'll mark this as an enhancement for PyDPF-Post.
